name: .NET


on:
  push:
    branches: [main]

env: 
  DOTNET_VERSION: '5'

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup .Net
        uses: actions/setup@-dotnet@v4
        with:
          dotnet.version: ${{env.DOTNET_VERSION}}

  Restore:
    needs: install 
    runs-on: ubuntu-latest
    steps:
            
      - name: restore dependies
        uses: dotnet restore
         with:
          dotnet.version: ${{env.DOTNET_VERSION}}

  Build:
    needs: Restore 
    runs-on: ubuntu-latest
    steps:
      - name: build .Net
        uses: dotnet build --configuration Release --no-restore


          
