name: test5

on:
  push:
    branches: [main]

jobs:
  Login:
    runs-on: ubuntu-latest

    steps:
      - name: first
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: '${{DOCKER_USER}}'
          password: '${{DOCKER_PASSWORD}}'
          

      - name: build2
        run: echo 'this is second line'
