name: .NET


on:
  push:
    branches: [main]

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the code
        uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: restore dependies
        shell: bash
        run: dotnet restore

      - name: build .Net
        run: dotnet build --configuration Release --no-restore

 
      - name: publish .NET
        run: dotnet publish -c Release -o ./publish
          
