name: .NET


on:
  push:
    branches: [main]

env: 
  DOTNET_VERSION: '5'

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: setup .Net
        uses: actions/setup@-dotnet@v4
        with:
          dotnet.version: ${{env.DOTNET_VERSION}}

      - name: restore dependies
        run: dotnet restore
         
          
      - name: build .Net
        run: dotnet publish -c Release -o ./publish



          
