name: test5

on:
  push:
    branches: [main]

jobs:
  Login:
    runs-on: ubuntu-latest

    steps:
      - name: first
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASSWORD}}
          

      - name: build2
        run: echo 'this is second line'

  NGINX:
    needs: Login
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: run nginx
        id: nginx 
      
