name: test5

on:
  push:
    branches: [main]

jobs:
  Login:
    runs-on: ubuntu-latest

    steps:
      - name: first
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASSWORD}}
          
  NGINX-SETUP:
    needs: Login
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v2

      - name: nginx setup
        run: |
          docker run -itd -P nginx
          
  HTTPD-SETUP:
    needs: NGINX-SETUP
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v2

      - name: nginx setup
        run: |
          docker run -itd -P httpd
        
  POST:
    needs: HTTPD-SETUP
    runs-on: windows-latest
    steps:
      - name: check the donctainer created
        run: echo 'check the code'  
      

      

      
