name: .NET
env:
  DOTNET_VERSION: '5'


on:
  push:
    branches: [main]

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the code
        uses: actions/checkput@v3
        
      - name: setup 
        uses: actions/setup@-dotnet@v3
        with:
          dotnet.version: ${{env.DOTNET_VERSION}}

  Restore:
    needs: install 
    runs-on: ubuntu-latest
    steps:
      
      - name: restore dependies
        run: dotnet restore

  Build:
    needs: Restore 
    runs-on: ubuntu-latest
    steps:
      - name: build .Net
        run: dotnet build --configuration Release --no-restore

  Publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: publish .NET
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}
          
