name: .NET
env:
  DOTNET_VERSION: '5'


on:
  push:
    branches: [main]

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the code
        uses: actions/checkout@v3
        
      - name: setup 
        uses: actions/setup@-dotnet@v3
        with:
          dotnet.version: ${{env.DOTNET_VERSION}}

      - name: restore dependies
        run: dotnet restore

      - name: build .Net
        run: dotnet build --configuration Release --no-restore

 
      - name: publish .NET
        run: dotnet publish -c Release -o .github/workflows
          
